### ISSUE TITLE
API key

### ISSUE THREAD

**Issue by GamerBremer** [Gertje823/magister-scraper#2]
waar kan ik de api bearer vinden?

**Comment by GamerBremer** [comment]
oh zou je niet kunnen zorgen dat hij inplaats van die token gewoon ww leerlingnummer en school vraagt in het script dan denk ik

**Comment by Gertje823** [comment]
Nadat je je credentials hebt ingevuld in het script zou hij nu automatisch in moeten loggen en de data op moeten halen.

**Comment by GamerBremer** [comment]
ik krijg deze error: 

> Logging in to Magister...
c:\Users\tobia\OneDrive - GSG Guido\LAT\Magister maar dan beter\Test1\magister scraper.py:36: DeprecationWarning: There is no current event loop
  asyncio.get_event_loop().run_until_complete(main())
Traceback (most recent call last):
  File "c:\Users\tobia\OneDrive - GSG Guido\LAT\Magister maar dan beter\Test1\magister scraper.py", line 36, in <module>
    asyncio.get_event_loop().run_until_complete(main())
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2544.0_x64__qbz5n2kfra8p0\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "c:\Users\tobia\OneDrive - GSG Guido\LAT\Magister maar dan beter\Test1\magister scraper.py", line 15, in main
    browser = await launch({"headless": True, "args": ["--start-maximized"]})
  File "C:\Users\tobia\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pyppeteer\launcher.py", line 307, in launch
    return await Launcher(options, **kwargs).launch()
  File "C:\Users\tobia\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pyppeteer\launcher.py", line 148, in launch
    self.proc = subprocess.Popen(  # type: ignore
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2544.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2544.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 1440, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
OSError: [WinError 14001] De toepassing kan niet worden gestart omdat de configuratie naast elkaar onjuist is. Raadpleeg het gebeurtenislogboek Toepassing of gebruik het opdrachtregelprogramma sxstrace.exe voor meer informatie

**Comment by Gertje823** [comment]
Heb je toevallig python geïnstalleerd vanuit de Windows store? Dat lijkt wel vaker voor problemen te zorgen met Pyppeteer. 
Kan je proberen om deze versie van python te verwijderen en de installer vanaf de officiële python site te downloaden en installeren?

**Comment by GamerBremer** [comment]
ik ga het proberen
